<?php
/**
 * This file is part of the Itabs_Invoice extension.
 *
 * @category  Itabs
 * @package   Itabs_Invoice
 * @author    Rouven Alexander Rieker <rouven.rieker@itabs.de>
 * @copyright 2013 ITABS GmbH (http://www.itabs.de/). All rights served.
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version   1.2.0
 * @link      https://github.com/itabs/Itabs_Invoice
 */
?>
<?php
/* @var $this Itabs_Invoice_Block_Info */

/* @var $method Itabs_Invoice_Model_Invoice */
$method = $this->getMethod();
?>
<p><?php echo $method->getTitle() ?></p>
<p><?php echo $this->__('Your invoice is payable within %s days.', $method->getConfigData('payment_due'))?></p>
<?php if ($method->getConfigData('text_block_info')): ?>
    <p><?php echo $method->getConfigData('text_block_info') ?></p>
<?php endif; ?>
