<?php
/**
 * This file is part of the Itabs_Invoice extension.
 *
 * @category  Itabs
 * @package   Itabs_Invoice
 * @author    ITABS GmbH <info@itabs.de>
 * @copyright 2013-2015 ITABS GmbH (http://www.itabs.de)
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version   1.3.0
 * @link      https://github.com/itabs/Itabs_Invoice
 */
?>
<?php
/* @var $this Itabs_Invoice_Block_Info */

/* @var $method Itabs_Invoice_Model_Invoice */
$method = $this->getMethod();
?>
<?php echo $this->escapeHtml($method->getTitle()) ?>
    {{pdf_row_separator}}
<?php if ($dueDate = $this->getDueDate()): ?>
    <?php echo $this->__('Your invoice is due on %s.', $dueDate)?>
<?php else: ?>
    <?php echo $this->__('Your invoice is payable within %s days.', $method->getConfigData('payment_due'))?>
<?php endif; ?>
    {{pdf_row_separator}}
<?php if ($method->getConfigData('text_block_info')): ?>
    <?php echo $method->getConfigData('text_block_info') ?>
<?php endif; ?>
